language: node_js
node_js:
  - '8'
cache:
  directories:
    - ./node_modules
    - ./react/node_modules
stages:
  - css
  - react
jobs:
  include:
    - stage: css
      script: npm run build
      deploy:
      - provider: surge
        domain: opensanca-burro.surge.sh
        project: ./dist
        on:
          tags: true
    - stage: react
      script: cd react && npm run test && npm run lint
      before_deploy:
        - npm run build
      deploy:
        provider: npm
        skip_cleanup: true
        email: guilherme.albino.francisco@gmail.com
        api_key:
            secure: QWYivc2Hvq40eYG73wd6Y2XwG5Q6bHi46Ei3wwqNcueAQrzCmadogtN2WjZGeexiOYoSADzNO0rdDw6TfTTh4wK4Zc27rPgmvhdUl5G160aE90zRbzX51aVfd0+hEFwrlWLVfWI9jvEX9mXWtPvarURueWxW6wJ/lbTjqaANwEt/OU1arp95Z4rtRfx4W+w9SYtdh8BxA2Imscc4PrO9ZvnwHrG/LrRLoBqNZKHRQzmSkXTCFrAsE2QsFHlTmaqbShHr522Qb/w2ci4p9bRRXCN5yGJSjIPBqXiw0CmGWQuJaAleu4F+M4cFxzeoahaqnnG5gXp6ANhAOK8ElcjoFm0XoC0/ZthAL3on/+qinpHnuqStwYeI140xrTQLA0TkGq+2aFpYhwAJYO6o/xNgjm8aOBw6oTDFQbUB7K+mAtGfziJ6LR91Yuk6sDgBjFnnb4HoylX3DlrCsUMfZ+xzUYkzseM3ErptJA67Pdkaq8meiF0dZFF6aHck7Fop+sQrtiLXlDykgT9uYiUaqJGDBeEEWaT1LDL3VS35MBl4FrU08T2Zgj9JJtc+vVGjm5UHpI2ZObsgPCBUktPc2j5bPq2imAuBaxJOZ+m+0r4TDJocJ5loC5rmy7r3+HRpmaG8vMJR1ERHzo4iNdX9YLTe5MTwAao337K/sQ0rpdERaOM=
        on:
          tags: true
env:
  global:
    secure: KJErYfj1KX9x474Ux8p1me14FRl9ig3MlyFbvDpDyB94lVK6tp5t1Y1eZG9O0hHzLTiHY6pCQEIXTQNfjmeVQcR76yqxpP3Exm76LHR7/YlxWvWTjxbrzoffRZ2jx7cLDSf3uLnzg8IyoX7XRnHRI0oLQdnsTUEn23szjr4am5/593bvqI/iggqS4zP+3BxS+mRqCOJdi9LBgG8IIrGTT7jXHTznT/JxfoTnVaPqr4Xi9waHL+yOKMcg98fjQdzZRBw0dWGW+kfB+HlHXXPF7p+pCgdNejm1vnpCZwS8eIuD2YMBTvphdebcnpI+Lei4XmkcLH0XSgydvT9lEf5ZYQ4NW2GuV5mdd1PiwsgI5WPyHvzJ1jObRFOQieGbfMYdfQqoL4VWoFeS3dGJyMPZPD4dX0hedWqA26ZzlmHn57I5zVcDbwX7+8o5nKkMUVrYGzOEhPsgSJjhqet+K7S9RnFOMekb6dhunh88LgkjpYfI7YlHTMswkZ+DR4I22JW8NUgXUExVTwflIUNINdTWM2B1XApibMlcXsDy24EQla/g2s3EftfKlPctAemRUmskrgg6zYo7tor15wQ6wYCKX+vovgupLDtkYgIQhTw/LnM7vYmbGaZsAUTWh8paenV5pJFRD/XwWC64SQUgT2DTSLUrLqNL1bBryuT9pb29OUw=
