language: node_js
node_js:
  - '8'
cache:
  directories:
    - ./node_modules
    - ./react/node_modules
stages:
  - css
  - react
jobs:
  include:
    - stage: css
      script: npm run build
      deploy:
      - provider: surge
        domain: opensanca-burro.surge.sh
        skip_cleanup: true
        project: ./dist
        on:
          tags: true
    - stage: react
      script: cd react && npm run test && npm run lint
      before_deploy:
        - npm run build
      deploy:
        provider: npm
        skip_cleanup: true
        email: guilherme.albino.francisco@gmail.com
        api_key:
            secure: regvB5QarxA6+JLW8T0o7X0WGuv7poBpB2TtWNExOZpnOc15jeU1aF0Bf3HhZWmhZf+nhGn2fj7iQ4PpBFrGnyc1diYdpvBqzO7JwcictdT79Z/qNtCEc1Or2u8VGwBM21wdDCuTnyIR88NzdhFVPX6VOmVZSj4qGgktabN9ZFcQinUvcTOOJ/hsa8pV0yoO/uw6PSoAXUjL21ZLabnbzGbSITQN43dxME6yC1eRgwNZdlNtUhy+C2H4FxvjLUIHGHnmnrvTZN2DgWVCZdq11X11BXrfPl/n7wXLmE05BkKKqYA/RdN3nEZD7flYh2VgtwILvxWqhpFfYauZrLozl6ySZK1angHjeTr9HzuyyLA+rxlJfTvrZ0MdgUTzUGQ5YFjshPuY9SUk0al+4AP7IVJ96H0uC85qlVsI/zTxwM7V6YmlYR6ooLN5T8YGpYdiEw3gSvGNo0jhSqelRI9DVlHLBpYCPAgI18uXQEXkKa7frksMi6d6FdwLlyqkq7apVWieCzPo0O1szP2vEWGCpNfo4hUPvXodFw/yd0dCCmSSRB5cv5UCPtAW1EOb+YZmS/MTcX2PWfBgSTXvmJ3Kg78s9IPWoCBi+FDE9uJhxC96BevDEzQMUplFFOQQnsyasM5Fcba+6Ompn6ZdfsfkgRZ7052ws38x5yGBsCg/F8s=
        on:
          tags: true
env:
  global:
    secure: KJErYfj1KX9x474Ux8p1me14FRl9ig3MlyFbvDpDyB94lVK6tp5t1Y1eZG9O0hHzLTiHY6pCQEIXTQNfjmeVQcR76yqxpP3Exm76LHR7/YlxWvWTjxbrzoffRZ2jx7cLDSf3uLnzg8IyoX7XRnHRI0oLQdnsTUEn23szjr4am5/593bvqI/iggqS4zP+3BxS+mRqCOJdi9LBgG8IIrGTT7jXHTznT/JxfoTnVaPqr4Xi9waHL+yOKMcg98fjQdzZRBw0dWGW+kfB+HlHXXPF7p+pCgdNejm1vnpCZwS8eIuD2YMBTvphdebcnpI+Lei4XmkcLH0XSgydvT9lEf5ZYQ4NW2GuV5mdd1PiwsgI5WPyHvzJ1jObRFOQieGbfMYdfQqoL4VWoFeS3dGJyMPZPD4dX0hedWqA26ZzlmHn57I5zVcDbwX7+8o5nKkMUVrYGzOEhPsgSJjhqet+K7S9RnFOMekb6dhunh88LgkjpYfI7YlHTMswkZ+DR4I22JW8NUgXUExVTwflIUNINdTWM2B1XApibMlcXsDy24EQla/g2s3EftfKlPctAemRUmskrgg6zYo7tor15wQ6wYCKX+vovgupLDtkYgIQhTw/LnM7vYmbGaZsAUTWh8paenV5pJFRD/XwWC64SQUgT2DTSLUrLqNL1bBryuT9pb29OUw=
