language: node_js
node_js:
  - '7'
install:
  - npm install
scripts:
  - npm run build:css
deploy:
  - provider: surge
    project: ./dist
    on: master
env:
  secure:
    - IemSVU4vc08Ggyau2PfePokWzorCbo7dspJ64fDOaau0Cn539yKd2lnCGQ0S1qeFBLCSEHPyax5cQT94hkbcKyNI1GiVG6ErVZAicjngPl7bMM+6rIToVi5jjk5uR4bX6g58MKGJ4Iim8Gb5AXK6AfcnCZFrgI2wrfmgeDaMuVclIb6wzKBQvcyk7irIOQo7prFebVO5i8BEyOkzem9t6t9RhDSFS5DYLkvC/i2fpEz1hm74TVZ7LXXc2oTZPaqcBFAVSy0nCuF8DQeabhldC2Ul6aE8bqaBVtOaQMzQ/8IZ2MQf3vkx8wsNgoAFbzRqUZdADEegn9dOsQ91JWr/GLR6iRb8wwvb7hVib7Rp7YJ+1HUT5pQmbjDCXF1ExCoLN9KyQzfqhitENr28OKSZ+p38ZY1DXNCp+AOC+87do3+w/dJQ5Uxrm2793ZZYYVwypQQaX11K/Fx2HLKBJPS5g0zGj7hf4XkTpkmcjS628lFt7NPmYLlyuTBDENSj0ohAoWnWuGYLvGbOycDcIq6cbT1gf3K9GahIsiQsjlAHBmPOKGgAk6AnM6wR1yy1fx7G/HFA6I9lm5T5cgPGxG2IfRBxcgNRzlZH0+1Cfxx3DoQPqRVudSweeGihoQlqE6zQElwkOko/UvZmSbWi0HyJPXhg3T1AIiMXxHZq7Ujz7VI=
    - fNQ0CrXYWiYlpcRSiRPaKU3yw/0UekyWmyy1OQazYRBjDfc3SPun0+fct9BAc3po8UwcOYYlJohjV3JkfG8Bsbtmgb3h/rQ/juEw4gWJwvQ80yzaTchEId0+h+MH46/B6TsVwsg27gnP0I5nXlmbDP81PkJTU6/LDos8LrplLinGRCdKZBWOCPxZVdpFwYay0EDSKJR57E0wmTSnbHz59JgMD5nly3xrXXkj/aUZNOWb2B4ml3k0dJOjkjuEK5FlS8Jd0tuHqxsjNPg48RgyRD0x/m98fgmxS7Ewpqo6rOCDk72PeZOE0IG/O4uKidDMjlmTjZNtb5/EcrICJSVD0rZkxRYuxsuwUPORrDp4vMpwx8Kg5RkxoDfp/YvJgG9M9UuHa0F1sd7/uGOPQ0bI2VKGxzMffhN/48ssRwnbfzMBmj3Tb8JYdMksvFenADmzy62uwxgwCRZzNl7cadYfVLBXxRfUa6spVT+nki00BXaGL5McuYD6RBLjycpmYcsf0+o/kdXJ1WQTBkpbGMJV57quuO4nWWHJnYy0AkZV9WrDgcqxKuJd2qMKIjIWf1YMRXcvPegWdOF9+5vOVxbkFqHr0MaxOxHL34sYOTia7KpKB7H+kR2POD4PvnGhKvC0hk7CYI3iBFVNWEeWq0vjOV3VsS9AktuNleL01gbj0pY=